# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c588f3cf0b227b096d7fd936d2500b28158a63b792f2c36d7c502807196cf6cf186ef4d913f625ce0a9f2c1f7e668782d8a060a7b5e80264a9de41a292a7e1e

test:
  secret_key_base: 50d197331578601a6252b4f1a38a94cf6223dad5c35a568a2272ddc9ec52327f6668cd796ef50971dcd2ae3da382b302d056f4ad730131228e9c0095a50f5a71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
